// Copyright 2023 Infrable. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package main is a generated GoMock package.
package main

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAllocationAPI is a mock of AllocationAPI interface.
type MockAllocationAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAllocationAPIMockRecorder
}

// MockAllocationAPIMockRecorder is the mock recorder for MockAllocationAPI.
type MockAllocationAPIMockRecorder struct {
	mock *MockAllocationAPI
}

// NewMockAllocationAPI creates a new mock instance.
func NewMockAllocationAPI(ctrl *gomock.Controller) *MockAllocationAPI {
	mock := &MockAllocationAPI{ctrl: ctrl}
	mock.recorder = &MockAllocationAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllocationAPI) EXPECT() *MockAllocationAPIMockRecorder {
	return m.recorder
}

// GetAllocation mocks base method.
func (m *MockAllocationAPI) GetAllocation(arg0 string) ([]Allocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllocation", arg0)
	ret0, _ := ret[0].([]Allocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllocation indicates an expected call of GetAllocation.
func (mr *MockAllocationAPIMockRecorder) GetAllocation(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllocation", reflect.TypeOf((*MockAllocationAPI)(nil).GetAllocation), arg0)
}

// GetURL mocks base method.
func (m *MockAllocationAPI) GetURL(arg0 string, arg1 int, arg2 string, arg3 map[string]any) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetURL indicates an expected call of GetURL.
func (mr *MockAllocationAPIMockRecorder) GetURL(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockAllocationAPI)(nil).GetURL), arg0, arg1, arg2, arg3)
}
