---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubecost-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost-exporter.labels" . | nindent 4 }}
data:
  config: |
    {{- .Values.config | toYaml | nindent 4 }}
