---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubecost-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "kubecost-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubecost-exporter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "kubecost-exporter.image" . }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.config.server.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            timeoutSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/config
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          env:
            - name: KUBECOST_EXPORTER_CONFIG_NAME
              value: kubecost-exporter
            - name: KUBECOST_EXPORTER_CONFIG_TYPE
              value: yaml
            - name: KUBECOST_EXPORTER_CONFIG_PATH
              value: /etc/config
      volumes:
        - name: config
          configMap:
            name: {{ include "kubecost-exporter.fullname" . }}
            items:
            - key: config
              path: kubecost-exporter.yaml
