name: Helm

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Test Helm chart"
    steps:
      # NOTE: You should use the checkout action any time your workflow will
      # run against the repository's code.
      # See: https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3
      # See: https://github.com/marketplace/actions/setup-minikube
      - uses: medyagh/setup-minikube@latest
      - name: "Install Helm"
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: "Lint, package and install Helm chart"
        run: |
          helm lint deploy/helm/kubecost-exporter
          helm package deploy/helm/kubecost-exporter
          helm install kubecost-exporter kubecost-exporter-*.tgz
          # debug
          sleep 30
          kubectl describe pods -l "app.kubernetes.io/name=kubecost-exporter"
      - name: "Test Helm chart installation"
        run: helm test kubecost-exporter
